
USE arg

-- добавление полей 
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.port_station_working ADD
	isPort tinyint NULL
GO
ALTER TABLE dbo.port_station_working ADD CONSTRAINT
	DF_port_station_working_isPort DEFAULT 1 FOR isPort
GO
ALTER TABLE dbo.port_station_working SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
