
USE prolong
-- добавление полей 
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DropProlong ADD
	responceID int NULL,
	responceTGNL int NULL
GO
ALTER TABLE dbo.DropProlong SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
